- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false 
  become: true
  tags:
    - load_balancers

  tasks:
    - name: Install firewall
      include_role: 
        name: firewall
      vars: 
        firewall_services:
          - http
        firewall_tcp_ports:
          - 8080
    
    - name: Install Load balancer
      include_role:
        name: haproxy