---
- name: Manage OpenStack Servers
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - openstack_manage_inmemory_inventory

- name: update resolve.conf
  hosts: load_balancers,app_servers,database_servers
  become: true
  tasks:
    #- debug:
        #msg: "{{ ansible_default_ipv4.address }}, {{ hostvars[ansible_default_ipv4.address].ansible_dns.nameservers.0 }}"
        #msg: "{{ ansible_dns.nameservers.0 }}, {{ ansible_dns.nameservers.1 }}"
    - name: Insert DNS IP
      command: >-
        nmcli connection modify "System eth0"
        ipv4.ignore-auto-dns yes
        ipv4.dns {{ ansible_dns.nameservers.0 }}
        +ipv4.dns 192.168.50.115 
        +ipv4.dns 8.8.8.8
    
    - name: Restart NetworkManager
      service:
        name: NetworkManager
        state: restarted

    - name: install katello-ca-customer package
      yum: 
        name: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
        disable_gpg_check: true
        state: present

    - name: register system and attach subs
      redhat_subscription:
        state: present
        username: "admin"
        password: "r3dh4t1!"
        auto_attach: true
